import { apiGetProducts } from "@/api/utils";
import "@/assets/scss/globals.scss";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ProductsProvider } from "@/provider/ProductsProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const productsData = await apiGetProducts();

  return (
    <html lang="en">
      <body className="relative">
        <ProductsProvider initialData={productsData}>
          <Header />
          {children}
          <Footer />
        </ProductsProvider>
      </body>
    </html>
  );
}
